class io.vertx.core.impl.future.Eventually extends io.vertx.core.impl.future.Operation implements io.vertx.core.impl.future.Listener
{
private final java.util.function.Function mapper;
void <init>(io.vertx.core.impl.ContextInternal, java.util.function.Function)
{
io.vertx.core.impl.ContextInternal v1;
io.vertx.core.impl.future.Eventually v0;
java.util.function.Function v2;
v0 := @this: io.vertx.core.impl.future.Eventually;
v1 := @parameter0: io.vertx.core.impl.ContextInternal;
v2 := @parameter1: java.util.function.Function;
specialinvoke v0.<io.vertx.core.impl.future.Operation: void <init>(io.vertx.core.impl.ContextInternal)>(v1);
v0.<io.vertx.core.impl.future.Eventually: java.util.function.Function mapper> = v2;
return;
}
public void onSuccess(java.lang.Object)
{
java.lang.Throwable v4;
io.vertx.core.impl.future.Eventually v0;
java.lang.Object v1, v3;
io.vertx.core.impl.future.Eventually$1 v5;
java.util.function.Function v2;
v0 := @this: io.vertx.core.impl.future.Eventually;
v1 := @parameter0: java.lang.Object;
label1:
v2 = v0.<io.vertx.core.impl.future.Eventually: java.util.function.Function mapper>;
v3 = interfaceinvoke v2.<java.util.function.Function: java.lang.Object apply(java.lang.Object)>(null);
label2:
goto label4;
label3:
v4 := @caughtexception;
virtualinvoke v0.<io.vertx.core.impl.future.Eventually: boolean tryFail(java.lang.Throwable)>(v4);
return;
label4:
v5 = new io.vertx.core.impl.future.Eventually$1;
specialinvoke v5.<io.vertx.core.impl.future.Eventually$1: void <init>(io.vertx.core.impl.future.Eventually,java.lang.Object)>(v0, v1);
interfaceinvoke v3.<io.vertx.core.impl.future.FutureInternal: void addListener(io.vertx.core.impl.future.Listener)>(v5);
return;
catch java.lang.Throwable from label1 to label2 with label3;
}
public void onFailure(java.lang.Throwable)
{
java.lang.Throwable v1, v4;
io.vertx.core.impl.future.Eventually v0;
java.lang.Object v3;
java.util.function.Function v2;
io.vertx.core.impl.future.Eventually$2 v5;
v0 := @this: io.vertx.core.impl.future.Eventually;
v1 := @parameter0: java.lang.Throwable;
label1:
v2 = v0.<io.vertx.core.impl.future.Eventually: java.util.function.Function mapper>;
v3 = interfaceinvoke v2.<java.util.function.Function: java.lang.Object apply(java.lang.Object)>(null);
label2:
goto label4;
label3:
v4 := @caughtexception;
virtualinvoke v0.<io.vertx.core.impl.future.Eventually: boolean tryFail(java.lang.Throwable)>(v4);
return;
label4:
v5 = new io.vertx.core.impl.future.Eventually$2;
specialinvoke v5.<io.vertx.core.impl.future.Eventually$2: void <init>(io.vertx.core.impl.future.Eventually,java.lang.Throwable)>(v0, v1);
interfaceinvoke v3.<io.vertx.core.impl.future.FutureInternal: void addListener(io.vertx.core.impl.future.Listener)>(v5);
return;
catch java.lang.Throwable from label1 to label2 with label3;
}
}